name: Spotlight Download Archive
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  download_archive:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Spotlight-Downloader.exe
        run: cmd /c start spotlight-download-archive.bat
      - name: Copy output files to repository folder
        run: Copy-Item -Path SpotlightArchive\* -Destination .\ -Recurse
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push changes to repository
        run: |
          git config user.name ${{ secrets.GITHUB_TOKEN }}
          git config user.email ${{ secrets.GITHUB_TOKEN }}
          git add .
          git commit -m "Update spotlight images"
          git push
