name: Spotlight Download Archive
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  download_archive:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: List directories and files before
        run: cmd /c dir /s
      - name: Run Spotlight-Downloader.bat
        run: cmd /c start spotlight-download-archive.bat
      - name: List directories and files after
        run: cmd /c dir /s
      - name: Configure git
        run:
          git config --local user.name github-actions
          git config --local user.email github-actions@github.com
      - name: Stage changes
        run: git add SpotlightArchive\*
      - name: Commit changes
        run: git commit -m "Update spotlight images"
      - name: Push changes
        run: git push origin master
